// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY2kwp_DfpNzUH68z9O3kGEejYgqblRxw',
    appId: '1:433705457709:web:170a67062f20a4fe4b40a4',
    messagingSenderId: '433705457709',
    projectId: 'zartek-task-1ac7d',
    authDomain: 'zartek-task-1ac7d.firebaseapp.com',
    storageBucket: 'zartek-task-1ac7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwtZkRsydVpbv1olxwVSo9bLsbpzKSpmc',
    appId: '1:433705457709:android:a0fe4a647cff53414b40a4',
    messagingSenderId: '433705457709',
    projectId: 'zartek-task-1ac7d',
    storageBucket: 'zartek-task-1ac7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5BugHGYmqwhW20KMuE9Jgu6P4vN6QjNs',
    appId: '1:433705457709:ios:c951b28bb953c0034b40a4',
    messagingSenderId: '433705457709',
    projectId: 'zartek-task-1ac7d',
    storageBucket: 'zartek-task-1ac7d.appspot.com',
    iosBundleId: 'com.zartekmachinetest.zartekMachineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5BugHGYmqwhW20KMuE9Jgu6P4vN6QjNs',
    appId: '1:433705457709:ios:c951b28bb953c0034b40a4',
    messagingSenderId: '433705457709',
    projectId: 'zartek-task-1ac7d',
    storageBucket: 'zartek-task-1ac7d.appspot.com',
    iosBundleId: 'com.zartekmachinetest.zartekMachineTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY2kwp_DfpNzUH68z9O3kGEejYgqblRxw',
    appId: '1:433705457709:web:d8e16d06e3d680ec4b40a4',
    messagingSenderId: '433705457709',
    projectId: 'zartek-task-1ac7d',
    authDomain: 'zartek-task-1ac7d.firebaseapp.com',
    storageBucket: 'zartek-task-1ac7d.appspot.com',
  );
}
